// SPDX-License-Identifier: GPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Mohamed Hammad

//! `zamak completions <shell>` — emit a completion script for the
//! requested shell. Supports bash, zsh, fish, and nushell.
//!
//! The script is plain text, written to stdout; no envelope
//! wrapping so that it can be sourced directly
//! (`source <(zamak completions bash)`).

use std::io::Write;

use crate::error::CliError;

pub fn run(args: &[String]) -> Result<(), CliError> {
    let shell = args
        .first()
        .map(|s| s.as_str())
        .ok_or_else(|| CliError::usage("completions: missing shell argument (bash|zsh|fish|nushell)"))?;

    if args.len() > 1 {
        return Err(CliError::usage(
            "completions: accepts exactly one positional argument",
        ));
    }

    let script = match shell {
        "bash" => BASH,
        "zsh" => ZSH,
        "fish" => FISH,
        "nushell" | "nu" => NUSHELL,
        other => {
            return Err(CliError::invalid(format!(
                "completions: unsupported shell '{other}' (expected bash|zsh|fish|nushell)"
            )))
        }
    };
    let stdout = std::io::stdout();
    let mut out = stdout.lock();
    out.write_all(script.as_bytes())
        .map_err(|e| CliError::from_io("completions: write stdout", e))?;
    Ok(())
}


const BASH: &str = r#"# zamak(1) bash completion — generated by `zamak completions bash`
_zamak() {
    local cur prev words cword
    _init_completion || return
    local cmds="install enroll-config sbom schema describe completions help"
    local globals="--json --format --fields --dry-run --verbose --quiet --color --no-color --yes --force --print0 -0 --help -h --version -V"
    if [[ $cword -eq 1 ]]; then
        COMPREPLY=($(compgen -W "$cmds $globals" -- "$cur"))
        return
    fi
    case "${words[1]}" in
        install)
            COMPREPLY=($(compgen -W "--mbr --stage2 --target --stage2-lba $globals" -- "$cur"))
            ;;
        enroll-config)
            COMPREPLY=($(compgen -W "--config --efi $globals" -- "$cur"))
            ;;
        sbom)
            COMPREPLY=($(compgen -W "--version --output -o $globals" -- "$cur"))
            ;;
        schema)
            COMPREPLY=($(compgen -W "install enroll-config sbom schema describe completions $globals" -- "$cur"))
            ;;
        completions)
            COMPREPLY=($(compgen -W "bash zsh fish nushell" -- "$cur"))
            ;;
        *)
            COMPREPLY=($(compgen -W "$globals" -- "$cur"))
            ;;
    esac
}
complete -F _zamak zamak
"#;

const ZSH: &str = r#"#compdef zamak
# zsh completion — generated by `zamak completions zsh`
_zamak() {
    local -a commands globals
    commands=(
        'install:Write stage1 MBR and record stage2 location'
        'enroll-config:Compute BLAKE2B config hash and patch EFI binary'
        'sbom:Generate SPDX 2.3 JSON SBOM'
        'schema:Emit JSON Schema for the whole tool or one command'
        'describe:Emit capability manifest'
        'completions:Emit shell completion script'
        'help:Show help'
    )
    globals=(
        '--json[machine-readable JSON output]'
        '--format[select output format]:format:(human json jsonl yaml csv explore)'
        '--fields[project to listed fields]:fields'
        '--dry-run[show planned actions without executing]'
        '-n[show planned actions without executing]'
        '--verbose[verbose diagnostics]'
        '-v[verbose diagnostics]'
        '--quiet[suppress info diagnostics]'
        '-q[suppress info diagnostics]'
        '--color[color mode]:mode:(auto always never)'
        '--no-color[disable color]'
        '--yes[skip confirmation prompts]'
        '-y[skip confirmation prompts]'
        '--force[force destructive operations]'
        '--print0[NUL-delimited path output]'
        '-0[NUL-delimited path output]'
        '--help[show help]'
        '-h[show help]'
        '--version[show version]'
        '-V[show version]'
    )
    _arguments -C \
        $globals \
        '1: :->cmd' \
        '*:: :->args'
    case $state in
        cmd) _describe 'command' commands ;;
        args)
            case $words[1] in
                completions) _values 'shell' bash zsh fish nushell ;;
                schema) _values 'command' install enroll-config sbom schema describe completions ;;
            esac
            ;;
    esac
}
compdef _zamak zamak
"#;

const FISH: &str = r#"# fish completion — generated by `zamak completions fish`
complete -c zamak -f
complete -c zamak -n '__fish_use_subcommand' -a install        -d 'Write stage1 MBR and record stage2 location'
complete -c zamak -n '__fish_use_subcommand' -a enroll-config  -d 'Compute BLAKE2B config hash and patch EFI binary'
complete -c zamak -n '__fish_use_subcommand' -a sbom           -d 'Generate SPDX 2.3 JSON SBOM'
complete -c zamak -n '__fish_use_subcommand' -a schema         -d 'Emit JSON Schema'
complete -c zamak -n '__fish_use_subcommand' -a describe       -d 'Emit capability manifest'
complete -c zamak -n '__fish_use_subcommand' -a completions    -d 'Emit shell completion script'
complete -c zamak -n '__fish_use_subcommand' -a help           -d 'Show help'

# Global flags (apply to every sub-command).
complete -c zamak -l json              -d 'Emit JSON'
complete -c zamak -l format -x -a 'human json jsonl yaml csv explore' -d 'Output format'
complete -c zamak -l fields -x         -d 'Comma-separated fields to keep'
complete -c zamak -l dry-run           -d 'Show planned actions'
complete -c zamak -s n                 -d 'Alias for --dry-run'
complete -c zamak -l verbose -s v      -d 'Verbose diagnostics'
complete -c zamak -l quiet -s q        -d 'Suppress info diagnostics'
complete -c zamak -l color -x -a 'auto always never' -d 'Color mode'
complete -c zamak -l no-color          -d 'Disable color'
complete -c zamak -l yes -s y          -d 'Skip confirmation prompts'
complete -c zamak -l force             -d 'Force destructive operations'
complete -c zamak -l print0 -s 0       -d 'NUL-delimited path output'
complete -c zamak -l help -s h         -d 'Show help'
complete -c zamak -l version -s V      -d 'Show version'

# Sub-command specific options.
complete -c zamak -n '__fish_seen_subcommand_from install' -l mbr        -r -d 'Path to stage1 MBR binary'
complete -c zamak -n '__fish_seen_subcommand_from install' -l stage2     -r -d 'Path to stage2 binary'
complete -c zamak -n '__fish_seen_subcommand_from install' -l target     -r -d 'Target device or image'
complete -c zamak -n '__fish_seen_subcommand_from install' -l stage2-lba -x -d 'LBA for stage2'
complete -c zamak -n '__fish_seen_subcommand_from enroll-config' -l config -r -d 'Path to zamak.conf'
complete -c zamak -n '__fish_seen_subcommand_from enroll-config' -l efi    -r -d 'Path to BOOTX64.EFI'
complete -c zamak -n '__fish_seen_subcommand_from sbom' -l version -x      -d 'ZAMAK release version'
complete -c zamak -n '__fish_seen_subcommand_from sbom' -l output -r -s o  -d 'Write SBOM to file'
complete -c zamak -n '__fish_seen_subcommand_from completions' -a 'bash zsh fish nushell' -d 'Target shell'
complete -c zamak -n '__fish_seen_subcommand_from schema'      -a 'install enroll-config sbom schema describe completions' -d 'Sub-command name'
"#;

const NUSHELL: &str = r#"# Nushell completion — generated by `zamak completions nushell`
# Source with:  source (zamak completions nushell | save --force /tmp/zamak.nu; echo /tmp/zamak.nu)
# Or simpler: zamak completions nushell | save -f ~/.config/nushell/zamak.nu
#             source ~/.config/nushell/zamak.nu

export extern "zamak install" [
    --mbr: path       # Path to stage1 MBR binary
    --stage2: path    # Path to stage2 binary
    --target: path    # Target device or image
    --stage2-lba: int # LBA where stage2 is written (default 1)
    --json            # Emit JSON envelope
    --format: string@"nu-complete zamak-format"
    --fields: string
    --dry-run (-n)    # Show planned actions without writing
    --verbose (-v)
    --quiet (-q)
    --color: string@"nu-complete zamak-color"
    --no-color
    --yes (-y)        # Skip confirmation
    --force           # Force destructive operation
    --print0 (-0)
    --help (-h)
]

export extern "zamak enroll-config" [
    --config: path    # Path to zamak.conf
    --efi: path       # Path to BOOTX64.EFI
    --json
    --format: string@"nu-complete zamak-format"
    --fields: string
    --dry-run (-n)
    --verbose (-v)
    --quiet (-q)
    --color: string@"nu-complete zamak-color"
    --no-color
    --yes (-y)
    --force
    --help (-h)
]

export extern "zamak sbom" [
    --version: string # ZAMAK release version
    --output (-o): path
    ...artifacts: path
    --json
    --format: string@"nu-complete zamak-format"
    --fields: string
    --color: string@"nu-complete zamak-color"
    --no-color
    --help (-h)
]

export extern "zamak schema" [
    command?: string@"nu-complete zamak-subcommand"
    --json
    --format: string@"nu-complete zamak-format"
]

export extern "zamak describe" [
    --json
    --format: string@"nu-complete zamak-format"
]

export extern "zamak completions" [
    shell: string@"nu-complete zamak-shell"
]

def "nu-complete zamak-format" [] { [ human json jsonl yaml csv explore ] }
def "nu-complete zamak-color"  [] { [ auto always never ] }
def "nu-complete zamak-shell"  [] { [ bash zsh fish nushell ] }
def "nu-complete zamak-subcommand" [] { [ install enroll-config sbom schema describe completions ] }
"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_completion_mentions_every_command() {
        for (shell, script) in
            [("bash", BASH), ("zsh", ZSH), ("fish", FISH), ("nushell", NUSHELL)]
        {
            for cmd in ["install", "enroll-config", "sbom", "schema", "describe"] {
                assert!(
                    script.contains(cmd),
                    "{shell} completion missing '{cmd}'"
                );
            }
        }
    }

    #[test]
    fn completions_enumerate_all_subcommand_names() {
        let commands = [
            "install",
            "enroll-config",
            "sbom",
            "schema",
            "describe",
            "completions",
            "help",
        ];
        for cmd in commands {
            assert!(BASH.contains(cmd), "bash missing {cmd}");
        }
    }
}
