# SPDX-License-Identifier: GPL-3.0-or-later
# Zamak cargo-deny configuration
# See https://embarkstudios.github.io/cargo-deny/
#
# Schema updated for cargo-deny >= 0.15 (EmbarkStudios/cargo-deny#611):
# the old per-severity keys (vulnerability/yanked/notice/unlicensed/
# copyleft) were removed. Advisories are now "deny by default"; use
# `[advisories.ignore]` for specific RUSTSEC-IDs. License policy is
# expressed solely through the `allow` list.

[advisories]
unmaintained = "workspace"

[licenses]
allow = [
    "GPL-3.0",
    "Apache-2.0",
    "MIT",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-3.0",
    "Unicode-DFS-2016",
    "MPL-2.0",
    "Zlib",
]

[bans]
multiple-versions = "warn"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
